language: php

php:
  - 5.6.21

sudo: required

env:
  global:
    - setup=basic
    - NODE_ENV=test
    - DB_CONNECTION=psql
    - PGPORT=5433
    - PGHOST=localhost
    - APP_ENV=staging
    - APP_DEBUG=true
    - APP_KEY=xxxx
    - CACHE_DRIVER=file
    - SESSION_DRIVER=file
    - QUEUE_DRIVER=sync

# matrix:
#   include:
#     - php: 5.5.9
#       env: setup=lowest
#     - php: 5.6.21
#       env: setup=stable

services:
  - postgresql

before_install:
  - travis_retry composer self-update
  - sudo apt-get install language-pack-es
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 9.5
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - cp .env.travis .env
  - psql -c 'create database adopets_test;' -U postgres
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

script: vendor/bin/phpunit
