language: php

php:
  - 5.6

matrix:
  allow_failures:
      - php: hhvm

services:
  - postgresql


before_script:
  - sudo apt-get update
  - sudo apt-get install language-pack-es
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 9.3
  - cp .env.travis .env
  - psql -c 'create database adopets_test;' -U postgres
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate


env:
  global:
    - setup=basic
    - APP_ENV=staging
    - APP_DEBUG=true
    - APP_KEY=xxxx
    - DB_CONNECTION=psql
    - CACHE_DRIVER=file
    - SESSION_DRIVER=file
    - QUEUE_DRIVER=sync

sudo: true

install:
- if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-source; fi
- if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-stable; fi
- if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - vendor/bin/phpunit
